apiVersion: v1
clusters:
- cluster:
    server: https://barely-sept-vehicles-lined.trycloudflare.com  
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjdYOS1GZ0xOX3dUbm1MSjc4NndjYnpoNlRkamJhSVNzeDd6THZzeDRNbEkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoZWxsby1rdWJlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwaS10dW5uZWwtYWRtaW4tdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBpLXR1bm5lbC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc1ZTYxMTk3LWYwMGYtNGRhNi1hMzU4LTZhY2Y1YWUwMTg4MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpoZWxsby1rdWJlOmFwaS10dW5uZWwtYWRtaW4ifQ.nTa03Alw5CqJZsmb5wrf7XIaGBCTIfVrZa9AyUhSY-2eMFePgNNPPgbLSUem-qOS8qD32qeyJdikGFptURl0hUx_OSsRtIUVaIxZefuO6R3cNxX0sempuqMnUr3s92_CkwSr5LHqrzra92Jzi2BfcHLaV-Imw8m00JXWa8krsba3qbvKMkia2khe57v6K96nyYhWg5JTCXKRznCmtU3fCQL6PrP-ZXy1EJHDK3CFkbzlQVByLF4EIvL3q_ILcAHsvyKzPNLztMedU61dW8OuEVBtnaaeu8WBg90obB0v5dxXo9vXpwxXATOnBr7JfkVPEna3nLuqNr-rfT01_Sw9Xw