apiVersion: v1
clusters:
- cluster:
    server: https://miss-investigation-cottages-metric.trycloudflare.com 
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImFOR2pfbjM3eDh1VGtXS0tiSEtCVlpSWG43VTBKYmQ2V2w3Q1dGVW1fR2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoZWxsby1rdWJlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwaS10dW5uZWwtYWRtaW4tdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBpLXR1bm5lbC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjlmNTE1ZDQzLTQ0M2EtNDllOS05NDhjLTJiYWE4OGIwMDA0ZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpoZWxsby1rdWJlOmFwaS10dW5uZWwtYWRtaW4ifQ.ZHWCRiQ0szPhxn8iTGhi8ZPslAGT8xyC2iRL0N7segbP2LBeLKkbWrBUVtBDXwbDbndsamEpexkinXNnEchpL821AsWJxIJjSAkEbwi79JZRzYL920n4ND23_s9J2Jv1JJanuuUer27znrMmMnhPs3ngmuZuo9TLpqwl6wLbzMW9DgY27CkW5C6dzSIuN4Y474yJonTHzh8Cd2IR7Bud7aip-u-a7dzXJgwszc5RNYmbveOQFKQilx3Uo_6Y-uPiQpQHGRtm_QZLNB-pZM30h55MNFFVBBlXdBeyb3kihaWNDwHIxQUS1KWuKZamOAqK30ACGBpRtgDOEhxlD9j6pQ