apiVersion: v1
clusters:
- cluster:
    server: https://mile-holdem-conference-met.trycloudflare.com
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Imp2WGhhcmhNN0RvMVBlVnU4SXczNlA5U3Z3NVUzM0dNSU1LbjJ3TTdKUnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoZWxsby1rdWJlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwaS10dW5uZWwtYWRtaW4tdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBpLXR1bm5lbC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc1ODMwMzFlLTMyNmItNDYyYi04MjU0LTNiMWViZGNkMDU0NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpoZWxsby1rdWJlOmFwaS10dW5uZWwtYWRtaW4ifQ.tXKDjmSCu2Q_uFzzYPCuxUbheLAEZ9HEMYe01MVDXV8W3lPW9JySirDdWwR1_SYwKdISngiEt4ot2IxAFdwl0pgmqzQC1tZBV0JHCZEPVaz_Dhpq8DbkCnXn5XpdIlYd6Wpe_L6cumuCJZCB87LgWYwvJEG9VM-YhL-gKUbqmGTaujQOnN8-UYafnyR_9G49zhOe0aDkpDSzl1qCTyWhREXWB7CAlqG1yWbT_uBlWQdwIBe1R9diDCXwSYLp6mApZco_0qzEsGTerRLVOYJh7inOZ4CeXHAqLGfqMXuf1W-a0GaFHYlYh3oDzinW2jyOQc0h4Uhu4aa6zeDueImFtA