apiVersion: v1
clusters:
- cluster:
    server: https://pi-clicks-modem-weed.trycloudflare.com  
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImFOR2pfbjM3eDh1VGtXS0tiSEtCVlpSWG43VTBKYmQ2V2w3Q1dGVW1fR2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoZWxsby1rdWJlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwaS10dW5uZWwtYWRtaW4tdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBpLXR1bm5lbC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjllMTlmOTkzLTQ3ZTctNDJhYS04NmJhLTkxMDFjMTBmYTkxMyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpoZWxsby1rdWJlOmFwaS10dW5uZWwtYWRtaW4ifQ.r1KegiNfZfhKjHFqNPrJGc3dX3ozpzGB5j7fus7ppdHJrRBJ4xdnqRpg69Vca6-wFSnN_OnN_0-a7TvDOoTg0ZhmxV3EB4Hwq4kNsNIYX7VLi8fvcwwd1sQ6A6eV4aU9V21KbIYYBdUXbVLyk1Fe5-ghWvi7g0UsuICi9wgzEPNnDuEi__Oz1sid7bNjIgrgU4p_3Akx2HgJvlykzvp1MRP29veY4mMdpQtHZiXjAZE0JfMcHUhO6F_r4-c60dVrwCKq4u-xmTvPelJjAhxv69bIZHf7UGQUlXuaK8nkLIE4Jf7ZX5nADAca58QpvH_-BEG0YP2waX7twuH7rqa-WQ