name: hello-compose

services:
  app:
    build: .
    ports:
      - 15000:5000

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  db-data: